docker build \
  --build-arg "OPENCLAW_IMAGE_APT_PACKAGES=${OPENCLAW_IMAGE_APT_PACKAGES}" \
  --build-arg "OPENCLAW_IMAGE_PIP_PACKAGES=${OPENCLAW_IMAGE_PIP_PACKAGES}" \
  --build-arg "OPENCLAW_IMAGE_NPM_PACKAGES=${OPENCLAW_IMAGE_NPM_PACKAGES}" \
  -t ${OPENCLAW_IMAGE} .
